"""
make_mysql_adventureworks.py — turn the public MySQL AdventureWorks dump
into two clean scripts you can import in MySQL Workbench.

WHY THIS EXISTS
---------------
The public dump names every table after its SQL Server schema, e.g.
`Person_Address`, `HumanResources_Employee`. Two problems:

1. Our word-matching stage splits on non-word characters but KEEPS
   underscores, so `HumanResources_Employee` is a single token. The word
   "employee" in a question would never match it, and the demo would look
   broken for the wrong reason.
2. Our published evaluation numbers were measured on the 68-table schema
   with plain names (`address`, `employee`, ...). We want the database on
   screen to be exactly the database we measured.

So this renames every table to its plain lowercase name and drops the 3
bookkeeping tables that are not part of the 68 (`awbuildversion`,
`databaselog`, `errorlog`).

It also splits the dump into schema and data, because a 100 MB single file
is painful in Workbench and because you asked for them separately.

USAGE
    python make_mysql_adventureworks.py <dump.sql> <output_dir>

OUTPUT
    adventureworks_mysql_schema.sql   small, run this first
    adventureworks_mysql_data.sql     large, run this second
"""

import os
import re
import sys

# not part of the 68-table AdventureWorks OLTP schema we evaluate on
EXCLUDE = {"awbuildversion", "databaselog", "errorlog"}

# a dump section header looks like:
#   --
#   -- Table structure for table `Person_Address`
#   --
SECTION = re.compile(
    r"\n--\n-- (Table structure for table|Dumping data for table) `([^`]+)`\n--\n"
)

HEADER = """-- AdventureWorks (OLTP) for MySQL — {kind}
-- Generated by make_mysql_adventureworks.py
--
-- Tables are renamed to their plain lowercase names (Person_Address ->
-- address) so this database matches the 68-table schema our evaluation
-- numbers were measured on.
--
-- Import order:  1) adventureworks_mysql_schema.sql
--                2) adventureworks_mysql_data.sql

CREATE DATABASE IF NOT EXISTS adventureworks
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE adventureworks;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET AUTOCOMMIT = 0;

"""

FOOTER = """
COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
"""


def plain(name: str) -> str:
    """'Person_Address' -> 'address';  'dbo_ErrorLog' -> 'errorlog'."""
    return (name.split("_", 1)[1] if "_" in name else name).lower()


def convert(dump_path: str, out_dir: str):
    with open(dump_path, encoding="utf-8", errors="replace") as f:
        text = f.read()

    parts = SECTION.split(text)
    # parts = [preamble, kind, name, body, kind, name, body, ...]
    schema_chunks, data_chunks = [], []
    renames, skipped = {}, set()

    for i in range(1, len(parts), 3):
        kind, raw_name, body = parts[i], parts[i + 1], parts[i + 2]
        new_name = plain(raw_name)

        if new_name in EXCLUDE:
            skipped.add(new_name)
            continue

        renames[raw_name] = new_name
        (schema_chunks if kind.startswith("Table structure") else data_chunks).append(body)

    def emit(chunks, kind, filename):
        body = "\n".join(chunks)
        # rename every backticked table identifier, longest first so that
        # e.g. `Sales_SalesOrderHeaderSalesReason` is not clipped by a
        # shorter prefix match
        for old in sorted(renames, key=len, reverse=True):
            body = body.replace(f"`{old}`", f"`{renames[old]}`")
        # drop the excluded tables' leftover references, if any
        for name in EXCLUDE:
            body = re.sub(rf"^.*`(?:dbo_)?{name}`.*$\n?", "", body,
                          flags=re.M | re.I)
        # MySQL 8/9 reject the 5.7 dump's binary payload for GEOMETRY
        # columns ("Cannot get geometry object from data you send").
        # AdventureWorks has exactly one (address.SpatialLocation) and it
        # plays no part in schema linking, so store it as a plain blob.
        body = body.replace("`SpatialLocation` geometry",
                            "`SpatialLocation` blob")

        path = os.path.join(out_dir, filename)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(HEADER.format(kind=kind) + body + FOOTER)
        return path, os.path.getsize(path)

    s_path, s_size = emit(schema_chunks, "schema (tables, keys, indexes)",
                          "adventureworks_mysql_schema.sql")
    d_path, d_size = emit(data_chunks, "data (INSERT statements)",
                          "adventureworks_mysql_data.sql")

    print(f"tables kept   : {len(renames) // 2 if len(renames) else 0} "
          f"(unique: {len(set(renames.values()))})")
    print(f"tables skipped: {sorted(skipped)}")
    print(f"schema -> {s_path}  ({s_size/1024:.0f} KB)")
    print(f"data   -> {d_path}  ({d_size/1024/1024:.1f} MB)")
    return s_path, d_path


def verify(schema_path: str, data_path: str):
    """Fail loudly if the rename left anything behind."""
    schema = open(schema_path, encoding="utf-8").read()

    created = re.findall(r"CREATE TABLE `([^`]+)`", schema)
    assert created, "no CREATE TABLE found"
    bad = [t for t in created if "_" in t and t.split("_", 1)[0].lower() in
           {"person", "sales", "production", "purchasing", "humanresources", "dbo"}]
    assert not bad, f"tables still schema-prefixed: {bad[:5]}"
    assert not (set(created) & EXCLUDE), f"excluded table survived: {set(created) & EXCLUDE}"

    fks = len(re.findall(r"FOREIGN KEY", schema))
    inserts = 0
    with open(data_path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("INSERT INTO"):
                inserts += 1

    print(f"\nverify: {len(created)} tables, {fks} foreign keys, "
          f"{inserts} INSERT statements — OK")
    return created


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    s, d = convert(sys.argv[1], sys.argv[2])
    verify(s, d)
